on: [push]
name: Deploy workflow
jobs:
  install:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # https://github.com/actions/deploy-pages
      pages: write
      id-token: write
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: true

      - name: Lint
        run: pnpm lint
      - name: Set git commit sha
        id: revparse
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Build
        run: pnpm build

      - name: Create Release
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Create Tar Ball
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        run: tar cJf yacd.tar.xz public
      - name: Upload Release Asset
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./yacd.tar.xz
          asset_name: yacd.tar.xz
          asset_content_type: application/x-gzip

      - name: Push to gh-pages
        #if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags/') || github.event.ref == 'refs/heads/publish')
        env:
          GITHUB_TOKEN: ${{ secrets.GITPAGE_TOKEN }}
          PUBLISH_DIR: public
          BRANCH: gh-pages
        run: |
          cd $PUBLISH_DIR
          ls -l
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@noreply.github.com"
          touch .nojekyll
          git add .
          git status
          git commit -m "Push to gh-pages"
          git push -f https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:$BRANCH
          echo "yacd.eu.org" > CNAME
          rm -rf .git/
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@noreply.github.com"
          git add .
          git commit -m "Push to gh-pages"
          git push -f https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/${GITHUB_ACTOR}/pageu.git HEAD:$BRANCH
          echo "yacd.clash-plus.tk" > CNAME
          rm -rf .git/
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@noreply.github.com"
          git add .
          git commit -m "Push to gh-pages"
          git push -f https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/${GITHUB_ACTOR}/pagek.git HEAD:$BRANCH
          echo "yacd.clash-plus.gq" > CNAME
          rm -rf .git/
          git init
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@noreply.github.com"
          git add .
          git commit -m "Push to gh-pages"
          git push -f https://$GITHUB_ACTOR:${GITHUB_TOKEN}@github.com/${GITHUB_ACTOR}/pageq.git HEAD:$BRANCH
